### ISSUE TITLE
Freeze axes and labels

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray-editor#29]
qtpy example : https://gist.github.com/gdementen/21a78ac56258c07dbc1072b806a5097a

Qt official example : http://doc.qt.io/qt-4.8/qt-itemviews-frozencolumn-example.html

make this more efficient : http://objexx.com/labs.Efficient-Qt-Frozen-Columns-and-Rows.html

**Comment by alixdamman** [comment]
Simple question: 
- the dictionary changes is not cleared in method accept_changes() of the ArrayModel. Is there a good reason for that ?

**Comment by alixdamman** [comment]
Other question: 
- Why having an "Apply" button? Why not applying changes directly?

**Comment by gdementen** [comment]
* changes not cleared in accept_changes seems like a small bug to me but this shouldn't have any grave consequence because in that case changes == data. It would be a good idea to clear it anyway because of potential side effects (array could still considered dirty or things like that).
* apply? That's historic. It mostly how it is done in spyder. I think applying changes directly would be better, but in that case we need to implement some undo functionality which might be a bit more complex to implement to reach what people except from undo/redo these days (ie multiple steps). Would be a nice to have though. We might want to open an issue for this...

**Comment by alixdamman** [comment]
In ArrayEditorWidget, the property `dirty` tests if lengh of changes is > 1. Why not 0?

**Comment by gdementen** [comment]
Ahem... because I was drunk when I wrote that code? Seriously, this is looks like just a stupid bug.
